language: go
dist: xenial
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
addons:
  apt:
    packages:
    - qemu-user-static
    - binfmt-support
script:
  - export GO111MODULE=on
  - diff -u <(echo -n) <(gofmt -d *.go)
  - diff -u <(echo -n) <(golint $(go list -e ./...) | grep -v YAMLToJSON)
  - go vet .
  - go test -v -race ./...
  - for arch in arm arm64 s390x ppc64le; do
      echo Cross test on $arch;
      GOARCH=$arch go test -v ./...;
    done
  - git diff --exit-code
install:
  - GO111MODULE=off go get golang.org/x/lint/golint
